- name: Install Apache on Web server
  hosts: 
    - ec2-184-73-113-235.compute-1.amazonaws.com
    - ec2-44-203-184-191.compute-1.amazonaws.com
  vars:
    app: apache2
  tasks:
    - name: Install Apache server
      apt:
        name: "{{ app }}"
        state: present
        update_cache: yes
      become: true

    - name: Start apache server
      service: 
        name: "{{ app }}"
        state: started
        enabled: yes
      become: true
