- name: Uninstall Apache on Web server
  hosts: 
    - web1
    - web2
    - web3
    - web4
    - loadbalancer
  vars:
    apps:
      - apache2
      - php
  tasks:
    - name: Uninstall Apache server
      apt:
        name: "{{ apps }}"
        state: absent
      become: true
